# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keepalive < Formula
  desc "A lightweight, cross-platform utility to prevent system sleep"
  homepage "https://github.com/stigoleg/keep-alive"
  version "1.3.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/stigoleg/keep-alive/releases/download/v1.3.5/keep-alive_Darwin_x86_64.tar.gz"
      sha256 "c8872bf28d987ab3353e7237c29a90e0c6ce0dd0ea40afff519828a63933e9fb"

      def install
        bin.install "keepalive"
      end
    end
    on_arm do
      url "https://github.com/stigoleg/keep-alive/releases/download/v1.3.5/keep-alive_Darwin_arm64.tar.gz"
      sha256 "2b9832adc35748ed6c908dea05048d5c213845eb7a976675788a7b861bfb6e26"

      def install
        bin.install "keepalive"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stigoleg/keep-alive/releases/download/v1.3.5/keep-alive_Linux_x86_64.tar.gz"
        sha256 "902a5f310701801e9179ef01fabb7ff04076f7049608650e405269b5003a3b21"

        def install
          bin.install "keepalive"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stigoleg/keep-alive/releases/download/v1.3.5/keep-alive_Linux_arm64.tar.gz"
        sha256 "aa98fc4937f2843a5ef0775a28343c0df5a238f22c02aab7e13a8925a08f7a78"

        def install
          bin.install "keepalive"
        end
      end
    end
  end
end
