# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keepalive < Formula
  desc "A lightweight, cross-platform utility to prevent system sleep"
  homepage "https://github.com/stigoleg/keep-alive"
  version "1.3.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/stigoleg/keep-alive/releases/download/v1.3.3/keep-alive_Darwin_x86_64.tar.gz"
      sha256 "1c9f76afa5b1d5face32e7b2f13bab7bb4af49039cc5a78a4a9ace847c3f42ec"

      def install
        bin.install "keepalive"
      end
    end
    on_arm do
      url "https://github.com/stigoleg/keep-alive/releases/download/v1.3.3/keep-alive_Darwin_arm64.tar.gz"
      sha256 "8921a53ba2e17fe3c8c9dd3a8c4a5a695ef5c8d685134c4076703a7e41fd0f45"

      def install
        bin.install "keepalive"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stigoleg/keep-alive/releases/download/v1.3.3/keep-alive_Linux_x86_64.tar.gz"
        sha256 "0eea7919e700a6c74203b9f2f0200023eac9af9063505ba0672762b62575bf63"

        def install
          bin.install "keepalive"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stigoleg/keep-alive/releases/download/v1.3.3/keep-alive_Linux_arm64.tar.gz"
        sha256 "ad0a1a4541ed8a1b4f65b038dcfc5fcd6da79d518ac510e16c2ef79bdf17cdd1"

        def install
          bin.install "keepalive"
        end
      end
    end
  end
end
